# Generated by Django 4.1.2 on 2022-11-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_artiste_first_name_alter_artiste_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='Song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='Artiste_id',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
