# Generated by Django 4.1.2 on 2022-11-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_artiste_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiste',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='artiste',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
    ]
