# Generated by Django 4.1.2 on 2022-11-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_remove_artiste_song_song_artiste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
    ]
