# Generated by Django 4.1.2 on 2022-11-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_song_artiste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Song_id',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='Artiste',
        ),
    ]
