# Generated by Django 4.1.2 on 2022-11-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_rename_song_id_lyric_song_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Artiste',
            new_name='artiste_id',
        ),
    ]
